import { jsPDF } from 'jspdf';
import { StartupProject } from '../types';

export function exportStartupToPdf(project: StartupProject): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper to add new page and reset Y
  function checkPageBreak(spaceNeeded: number) {
    if (y + spaceNeeded > pageHeight - margin - 15) {
      doc.addPage();
      y = margin + 10;
      addHeaderFooter();
    }
  }

  function addHeaderFooter() {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      // Header
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(140, 140, 140);
      doc.text(
        `AI STARTUP STUDIO — ${project.concept?.startupName || project.name || 'Startup Blueprint'}`.toUpperCase(),
        margin,
        12
      );
      doc.text('CONFIDENTIAL & PROPRIETARY', pageWidth - margin, 12, { align: 'right' });

      // Header line
      doc.setDrawColor(230, 230, 230);
      doc.setLineWidth(0.3);
      doc.line(margin, 14, pageWidth - margin, 14);

      // Footer line
      doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);

      // Footer
      doc.text(
        `Generated by AI Startup Studio · ${new Date().toLocaleDateString()}`,
        margin,
        pageHeight - 10
      );
      doc.text(`Page ${i}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    }
  }

  // Section Header Helper
  function renderSectionHeader(title: string, subtitle?: string) {
    checkPageBreak(25);
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59); // Slate 800
    doc.text(title.toUpperCase(), margin, y);

    // Accent bar
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(margin, y + 2, 28, 1.5, 'F');

    y += 8;
    if (subtitle) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(subtitle, margin, y);
      y += 6;
    }
  }

  // Paragraph helper
  function renderParagraph(label: string, text: string, spaceAfter = 6) {
    checkPageBreak(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(label, margin, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(text, contentWidth);
    for (const line of lines) {
      checkPageBreak(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += spaceAfter;
  }

  // Bullet items helper
  function renderBullets(label: string, items: string[]) {
    checkPageBreak(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(label, margin, y);
    y += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    items.forEach((item) => {
      checkPageBreak(7);
      const lines = doc.splitTextToSize(`•  ${item}`, contentWidth - 4);
      lines.forEach((line: string) => {
        doc.text(line, margin + 2, y);
        y += 4.5;
      });
    });
    y += 4;
  }

  // --- COVER / TITLE BLOCK ---
  y = 28;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  doc.setTextColor(15, 23, 42);
  doc.text(project.concept?.startupName || project.name || 'Startup Blueprint', margin, y);
  y += 9;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(13);
  doc.setTextColor(79, 70, 229);
  doc.text(project.concept?.tagline || project.industry || 'Venture Concept & Launch Plan', margin, y);
  y += 8;

  // Metadata pill box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, contentWidth, 14, 2, 2, 'FD');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`Industry: ${project.concept?.suggestedIndustry || project.industry}`, margin + 5, y + 6);
  doc.text(`Stage: Seed / Pre-Launch`, margin + 5, y + 10.5);
  doc.text(`Completion: ${project.completionPercentage}%`, margin + contentWidth / 2, y + 6);
  doc.text(`Created: ${new Date(project.createdAt).toLocaleDateString()}`, margin + contentWidth / 2, y + 10.5);
  y += 22;

  // --- 1. EXECUTIVE SUMMARY & CONCEPT ---
  renderSectionHeader('1. Executive Concept & Value Proposition');

  if (project.concept?.oneLinePitch) {
    renderParagraph('One-Line Elevator Pitch', project.concept.oneLinePitch);
  }

  if (project.concept?.problem) {
    renderParagraph('The Problem & Market Friction', project.concept.problem);
  }

  if (project.concept?.solution) {
    renderParagraph('The Breakthrough Solution', project.concept.solution);
  }

  if (project.concept?.valueProposition) {
    renderParagraph('Core Value Proposition', project.concept.valueProposition);
  }

  if (project.concept?.keyFeatures && project.concept.keyFeatures.length > 0) {
    renderBullets('Core Product Capabilities', project.concept.keyFeatures);
  }

  if (project.concept?.competitiveAdvantage) {
    renderParagraph('Competitive Advantage & Moat', project.concept.competitiveAdvantage);
  }

  // --- 2. BRAND IDENTITY & POSITIONING ---
  if (project.branding) {
    renderSectionHeader('2. Brand Identity & Strategy');

    renderParagraph('Brand Story & Origin Ethos', project.branding.brandStory);
    renderParagraph('Mission & Vision', `Mission: ${project.branding.mission}\nVision: ${project.branding.vision}`);

    if (project.branding.brandPersonality) {
      renderBullets('Brand Personality Pillars', project.branding.brandPersonality);
    }

    // Color Swatches
    checkPageBreak(30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text('Color Harmony Palette', margin, y);
    y += 6;

    const colors = [
      project.branding.colors.primary,
      project.branding.colors.secondary,
      project.branding.colors.accent,
      project.branding.colors.neutral,
    ];

    const swatchWidth = contentWidth / 4 - 3;
    colors.forEach((col, idx) => {
      const xPos = margin + idx * (swatchWidth + 4);
      // Convert hex to rgb
      const hex = col.hex.replace('#', '');
      const r = parseInt(hex.substring(0, 2), 16) || 40;
      const g = parseInt(hex.substring(2, 4), 16) || 40;
      const b = parseInt(hex.substring(4, 6), 16) || 40;

      doc.setFillColor(r, g, b);
      doc.roundedRect(xPos, y, swatchWidth, 10, 1.5, 1.5, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(15, 23, 42);
      doc.text(col.name, xPos, y + 14);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(col.hex, xPos, y + 18);
    });
    y += 24;
  }

  // --- 3. MARKET RESEARCH & SIZING ---
  if (project.marketResearch) {
    renderSectionHeader('3. Market Intelligence & Analysis', 'AI-Generated Hypotheses and Industry Estimates');

    const m = project.marketResearch;
    // Market sizing table
    checkPageBreak(35);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, contentWidth, 22, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text('TOTAL ADDRESSABLE MARKET (TAM)', margin + 4, y + 6);
    doc.text('SERVICEABLE MARKET (SAM)', margin + contentWidth / 3 + 2, y + 6);
    doc.text('OBTAINABLE MARKET (SOM)', margin + (contentWidth / 3) * 2 + 2, y + 6);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(m.marketOverview.tam || 'N/A', margin + 4, y + 13);
    doc.text(m.marketOverview.sam || 'N/A', margin + contentWidth / 3 + 2, y + 13);
    doc.text(m.marketOverview.som || 'N/A', margin + (contentWidth / 3) * 2 + 2, y + 13);

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`Estimated Growth: ${m.marketOverview.growthRate}`, margin + 4, y + 18);
    y += 28;

    renderParagraph('Market Summary & Driving Forces', m.marketOverview.summary);
    renderParagraph('Positioning Statement', m.positioningStatement);

    // SWOT
    if (m.swot) {
      checkPageBreak(40);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text('SWOT Strategic Matrix', margin, y);
      y += 6;

      const swotWidth = contentWidth / 2 - 3;
      const swotHeight = 28;

      // Strengths
      doc.setFillColor(240, 253, 244);
      doc.roundedRect(margin, y, swotWidth, swotHeight, 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(22, 101, 52);
      doc.text('STRENGTHS', margin + 3, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      m.swot.strengths.slice(0, 3).forEach((s, idx) => {
        doc.text(`• ${s.substring(0, 52)}`, margin + 3, y + 10 + idx * 5);
      });

      // Weaknesses
      doc.setFillColor(254, 242, 242);
      doc.roundedRect(margin + swotWidth + 6, y, swotWidth, swotHeight, 1.5, 1.5, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(153, 27, 27);
      doc.text('WEAKNESSES', margin + swotWidth + 9, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      m.swot.weaknesses.slice(0, 3).forEach((w, idx) => {
        doc.text(`• ${w.substring(0, 52)}`, margin + swotWidth + 9, y + 10 + idx * 5);
      });

      y += swotHeight + 10;
    }
  }

  // --- 4. BUSINESS MODEL CANVAS ---
  if (project.businessModelCanvas) {
    renderSectionHeader('4. Business Model Canvas (9-Block Matrix)');
    const b = project.businessModelCanvas;

    const sections = [
      { title: 'Value Propositions', items: b.valuePropositions },
      { title: 'Customer Segments', items: b.customerSegments },
      { title: 'Revenue Streams', items: b.revenueStreams },
      { title: 'Cost Structure', items: b.costStructure },
      { title: 'Key Activities', items: b.keyActivities },
      { title: 'Key Partners', items: b.keyPartners },
      { title: 'Key Resources', items: b.keyResources },
      { title: 'Channels', items: b.channels },
      { title: 'Customer Relationships', items: b.customerRelationships },
    ];

    sections.forEach((sec) => {
      if (sec.items && sec.items.length > 0) {
        renderBullets(sec.title, sec.items);
      }
    });
  }

  // --- 5. LAUNCH ROADMAP ---
  if (project.launchPlan) {
    renderSectionHeader('5. Launch Strategy & Roadmap');
    const lp = project.launchPlan;

    if (lp.preLaunch && lp.preLaunch.length > 0) {
      renderBullets(
        'Pre-Launch Phase (Validation & Preparation)',
        lp.preLaunch.map((t) => `[${t.timeline}] ${t.title}: ${t.description}`)
      );
    }

    if (lp.launch && lp.launch.length > 0) {
      renderBullets(
        'Launch Phase (Distribution Blitz)',
        lp.launch.map((t) => `[${t.timeline}] ${t.title}: ${t.description}`)
      );
    }

    if (lp.postLaunch && lp.postLaunch.length > 0) {
      renderBullets(
        'Post-Launch Phase (Growth & Retention)',
        lp.postLaunch.map((t) => `[${t.timeline}] ${t.title}: ${t.description}`)
      );
    }
  }

  // Add final page numbers & headers
  addHeaderFooter();

  // Trigger download
  const safeName = (project.concept?.startupName || project.name || 'Startup')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-');
  doc.save(`${safeName}-startup-blueprint.pdf`);
}
